#############################################################################
# Makefile for building: ASearch
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  Asearch.pro
# Template: app
# Command: /anaconda3/bin/qmake -o Makefile Asearch.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -std=c++11 -O2 -Wall -Wextra -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/anaconda3/include/qt -I/anaconda3/include/qt/QtGui -I/anaconda3/include/qt/QtCore -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I/anaconda3/mkspecs/macx-clang
QMAKE         = /anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ASearch1.0.0
DISTDIR = /Users/Igor/Documents/pathPlanning/proj2/astar_mac/.tmp/ASearch1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/anaconda3/lib
LIBS          = $(SUBLIBS) -L/anaconda3/lib -lQt5Gui -framework DiskArbitration -framework IOKit -lQt5Core -framework OpenGL -framework AGL 
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = tinyxml2.cpp \
		xmllogger.cpp \
		isearch.cpp \
		mission.cpp \
		map.cpp \
		dijkstra.cpp \
		config.cpp \
		astar.cpp \
		main.cpp \
		environmentoptions.cpp 
OBJECTS       = tinyxml2.o \
		xmllogger.o \
		isearch.o \
		mission.o \
		map.o \
		dijkstra.o \
		config.o \
		astar.o \
		main.o \
		environmentoptions.o
DIST          = /anaconda3/mkspecs/features/spec_pre.prf \
		/anaconda3/mkspecs/qdevice.pri \
		/anaconda3/mkspecs/features/device_config.prf \
		/anaconda3/mkspecs/common/unix.conf \
		/anaconda3/mkspecs/common/mac.conf \
		/anaconda3/mkspecs/common/macx.conf \
		/anaconda3/mkspecs/common/sanitize.conf \
		/anaconda3/mkspecs/common/gcc-base.conf \
		/anaconda3/mkspecs/common/gcc-base-mac.conf \
		/anaconda3/mkspecs/common/clang.conf \
		/anaconda3/mkspecs/common/clang-mac.conf \
		/anaconda3/mkspecs/qconfig.pri \
		/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/anaconda3/mkspecs/features/qt_functions.prf \
		/anaconda3/mkspecs/features/qt_config.prf \
		/anaconda3/mkspecs/macx-clang/qmake.conf \
		/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/anaconda3/mkspecs/features/exclusive_builds.prf \
		/anaconda3/mkspecs/features/mac/sdk.prf \
		/anaconda3/mkspecs/features/toolchain.prf \
		/anaconda3/mkspecs/features/mac/toolchain.prf \
		/anaconda3/mkspecs/features/default_pre.prf \
		/anaconda3/mkspecs/features/mac/default_pre.prf \
		/anaconda3/mkspecs/features/resolve_config.prf \
		/anaconda3/mkspecs/features/default_post.prf \
		/anaconda3/mkspecs/features/mac/default_post.prf \
		/anaconda3/mkspecs/features/mac/objective_c.prf \
		/anaconda3/mkspecs/features/warn_on.prf \
		/anaconda3/mkspecs/features/qt.prf \
		/anaconda3/mkspecs/features/resources.prf \
		/anaconda3/mkspecs/features/moc.prf \
		/anaconda3/mkspecs/features/unix/opengl.prf \
		/anaconda3/mkspecs/features/unix/thread.prf \
		/anaconda3/mkspecs/features/qmake_use.prf \
		/anaconda3/mkspecs/features/file_copies.prf \
		/anaconda3/mkspecs/features/mac/rez.prf \
		/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		/anaconda3/mkspecs/features/testcase_targets.prf \
		/anaconda3/mkspecs/features/exceptions.prf \
		/anaconda3/mkspecs/features/yacc.prf \
		/anaconda3/mkspecs/features/lex.prf \
		Asearch.pro tinyxml2.h \
		node.h \
		gl_const.h \
		xmllogger.h \
		isearch.h \
		mission.h \
		map.h \
		ilogger.h \
		dijkstra.h \
		config.h \
		astar.h \
		searchresult.h \
		environmentoptions.h tinyxml2.cpp \
		xmllogger.cpp \
		isearch.cpp \
		mission.cpp \
		map.cpp \
		dijkstra.cpp \
		config.cpp \
		astar.cpp \
		main.cpp \
		environmentoptions.cpp
QMAKE_TARGET  = ASearch
DESTDIR       = 
TARGET        = ASearch

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Asearch.pro /anaconda3/mkspecs/macx-clang/qmake.conf /anaconda3/mkspecs/features/spec_pre.prf \
		/anaconda3/mkspecs/qdevice.pri \
		/anaconda3/mkspecs/features/device_config.prf \
		/anaconda3/mkspecs/common/unix.conf \
		/anaconda3/mkspecs/common/mac.conf \
		/anaconda3/mkspecs/common/macx.conf \
		/anaconda3/mkspecs/common/sanitize.conf \
		/anaconda3/mkspecs/common/gcc-base.conf \
		/anaconda3/mkspecs/common/gcc-base-mac.conf \
		/anaconda3/mkspecs/common/clang.conf \
		/anaconda3/mkspecs/common/clang-mac.conf \
		/anaconda3/mkspecs/qconfig.pri \
		/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/anaconda3/mkspecs/features/qt_functions.prf \
		/anaconda3/mkspecs/features/qt_config.prf \
		/anaconda3/mkspecs/macx-clang/qmake.conf \
		/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/anaconda3/mkspecs/features/exclusive_builds.prf \
		/anaconda3/mkspecs/features/mac/sdk.prf \
		/anaconda3/mkspecs/features/toolchain.prf \
		/anaconda3/mkspecs/features/mac/toolchain.prf \
		/anaconda3/mkspecs/features/default_pre.prf \
		/anaconda3/mkspecs/features/mac/default_pre.prf \
		/anaconda3/mkspecs/features/resolve_config.prf \
		/anaconda3/mkspecs/features/default_post.prf \
		/anaconda3/mkspecs/features/mac/default_post.prf \
		/anaconda3/mkspecs/features/mac/objective_c.prf \
		/anaconda3/mkspecs/features/warn_on.prf \
		/anaconda3/mkspecs/features/qt.prf \
		/anaconda3/mkspecs/features/resources.prf \
		/anaconda3/mkspecs/features/moc.prf \
		/anaconda3/mkspecs/features/unix/opengl.prf \
		/anaconda3/mkspecs/features/unix/thread.prf \
		/anaconda3/mkspecs/features/qmake_use.prf \
		/anaconda3/mkspecs/features/file_copies.prf \
		/anaconda3/mkspecs/features/mac/rez.prf \
		/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		/anaconda3/mkspecs/features/testcase_targets.prf \
		/anaconda3/mkspecs/features/exceptions.prf \
		/anaconda3/mkspecs/features/yacc.prf \
		/anaconda3/mkspecs/features/lex.prf \
		Asearch.pro \
		/anaconda3/lib/libQt5Gui.prl \
		/anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Asearch.pro
/anaconda3/mkspecs/features/spec_pre.prf:
/anaconda3/mkspecs/qdevice.pri:
/anaconda3/mkspecs/features/device_config.prf:
/anaconda3/mkspecs/common/unix.conf:
/anaconda3/mkspecs/common/mac.conf:
/anaconda3/mkspecs/common/macx.conf:
/anaconda3/mkspecs/common/sanitize.conf:
/anaconda3/mkspecs/common/gcc-base.conf:
/anaconda3/mkspecs/common/gcc-base-mac.conf:
/anaconda3/mkspecs/common/clang.conf:
/anaconda3/mkspecs/common/clang-mac.conf:
/anaconda3/mkspecs/qconfig.pri:
/anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3drender.pri:
/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_charts.pri:
/anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
/anaconda3/mkspecs/modules/qt_lib_core.pri:
/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
/anaconda3/mkspecs/modules/qt_lib_designer.pri:
/anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_gui.pri:
/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
/anaconda3/mkspecs/modules/qt_lib_help.pri:
/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
/anaconda3/mkspecs/modules/qt_lib_location.pri:
/anaconda3/mkspecs/modules/qt_lib_location_private.pri:
/anaconda3/mkspecs/modules/qt_lib_macextras.pri:
/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri:
/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_network.pri:
/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
/anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_positioning.pri:
/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
/anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qml.pri:
/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quick.pri:
/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/anaconda3/mkspecs/modules/qt_lib_repparser.pri:
/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
/anaconda3/mkspecs/modules/qt_lib_script.pri:
/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
/anaconda3/mkspecs/modules/qt_lib_scxml.pri:
/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
/anaconda3/mkspecs/modules/qt_lib_sensors.pri:
/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
/anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
/anaconda3/mkspecs/modules/qt_lib_serialport.pri:
/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
/anaconda3/mkspecs/modules/qt_lib_sql.pri:
/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
/anaconda3/mkspecs/modules/qt_lib_svg.pri:
/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webengine.pri:
/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webview.pri:
/anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_xml.pri:
/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/anaconda3/mkspecs/features/qt_functions.prf:
/anaconda3/mkspecs/features/qt_config.prf:
/anaconda3/mkspecs/macx-clang/qmake.conf:
/anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
/anaconda3/mkspecs/features/exclusive_builds.prf:
/anaconda3/mkspecs/features/mac/sdk.prf:
/anaconda3/mkspecs/features/toolchain.prf:
/anaconda3/mkspecs/features/mac/toolchain.prf:
/anaconda3/mkspecs/features/default_pre.prf:
/anaconda3/mkspecs/features/mac/default_pre.prf:
/anaconda3/mkspecs/features/resolve_config.prf:
/anaconda3/mkspecs/features/default_post.prf:
/anaconda3/mkspecs/features/mac/default_post.prf:
/anaconda3/mkspecs/features/mac/objective_c.prf:
/anaconda3/mkspecs/features/warn_on.prf:
/anaconda3/mkspecs/features/qt.prf:
/anaconda3/mkspecs/features/resources.prf:
/anaconda3/mkspecs/features/moc.prf:
/anaconda3/mkspecs/features/unix/opengl.prf:
/anaconda3/mkspecs/features/unix/thread.prf:
/anaconda3/mkspecs/features/qmake_use.prf:
/anaconda3/mkspecs/features/file_copies.prf:
/anaconda3/mkspecs/features/mac/rez.prf:
/anaconda3/mkspecs/features/mac/asset_catalogs.prf:
/anaconda3/mkspecs/features/testcase_targets.prf:
/anaconda3/mkspecs/features/exceptions.prf:
/anaconda3/mkspecs/features/yacc.prf:
/anaconda3/mkspecs/features/lex.prf:
Asearch.pro:
/anaconda3/lib/libQt5Gui.prl:
/anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Asearch.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents tinyxml2.h node.h gl_const.h xmllogger.h isearch.h mission.h map.h ilogger.h dijkstra.h config.h astar.h searchresult.h environmentoptions.h $(DISTDIR)/
	$(COPY_FILE) --parents tinyxml2.cpp xmllogger.cpp isearch.cpp mission.cpp map.cpp dijkstra.cpp config.cpp astar.cpp main.cpp environmentoptions.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /anaconda3/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -std=c++11 -O2 -Wall -Wextra -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

tinyxml2.o: tinyxml2.cpp tinyxml2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxml2.o tinyxml2.cpp

xmllogger.o: xmllogger.cpp xmllogger.h \
		tinyxml2.h \
		ilogger.h \
		map.h \
		gl_const.h \
		node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmllogger.o xmllogger.cpp

isearch.o: isearch.cpp isearch.h \
		ilogger.h \
		map.h \
		gl_const.h \
		tinyxml2.h \
		node.h \
		searchresult.h \
		environmentoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o isearch.o isearch.cpp

mission.o: mission.cpp mission.h \
		map.h \
		gl_const.h \
		tinyxml2.h \
		config.h \
		isearch.h \
		ilogger.h \
		node.h \
		searchresult.h \
		environmentoptions.h \
		astar.h \
		dijkstra.h \
		xmllogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mission.o mission.cpp

map.o: map.cpp map.h \
		gl_const.h \
		tinyxml2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.o map.cpp

dijkstra.o: dijkstra.cpp dijkstra.h \
		astar.h \
		isearch.h \
		ilogger.h \
		map.h \
		gl_const.h \
		tinyxml2.h \
		node.h \
		searchresult.h \
		environmentoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dijkstra.o dijkstra.cpp

config.o: config.cpp config.h \
		gl_const.h \
		tinyxml2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

astar.o: astar.cpp astar.h \
		isearch.h \
		ilogger.h \
		map.h \
		gl_const.h \
		tinyxml2.h \
		node.h \
		searchresult.h \
		environmentoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o astar.o astar.cpp

main.o: main.cpp mission.h \
		map.h \
		gl_const.h \
		tinyxml2.h \
		config.h \
		isearch.h \
		ilogger.h \
		node.h \
		searchresult.h \
		environmentoptions.h \
		astar.h \
		dijkstra.h \
		xmllogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

environmentoptions.o: environmentoptions.cpp environmentoptions.h \
		gl_const.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o environmentoptions.o environmentoptions.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

